# Generated by Django 4.2.14 on 2024-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='use1',
            options={},
        ),
        migrations.AlterModelManagers(
            name='use1',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='use1',
            name='username',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Default Option 1', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Default Option 2', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Default Option 3', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Default Option 4', max_length=255),
        ),
    ]
