# Generated by Django 4.2.14 on 2024-07-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_use1_options_alter_use1_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='content_url',
        ),
    ]
